# Generated by Django 4.2.27 on 2026-01-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='Ид пользователя')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма выплаты')),
                ('payout_method', models.CharField(choices=[('bank_card', 'Bank card'), ('sbp', 'SBP')], max_length=32)),
                ('payout_details', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
            ],
        ),
    ]
